language: go

go:
  - 1.12

env:
  - GO111MODULE=on

matrix:
  fast_finish: true

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go vet -x ./...
  - go test -v -race ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken BM8PdGCDLUeZUEVwCWcziWhILae4MrcTI

after_success:
  - bash <(curl -s https://codecov.io/bash)
